server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456

    #使用druid连接池   https://blog.csdn.net/gnail_oug/article/details/80172239
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 30     # 最大连接池数量
      min-idle: 5        # 最小连接池数量
      max-wait: 60000    # 获取连接时最大等待时间，单位毫秒
      time-between-eviction-runs-millis: 30000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      validation-query: SELECT 1 FROM test # 用来检测连接是否有效的sql

mybatis:
  mapper-locations: classpath*:/mapping/*.xml
  type-aliases-package: com.ananopsmaster.eureka.company.demo.model